# Prettier (formatter) configuration
---
printWidth: 120
tabWidth: 4
useTabs: false
semi: true
singleQuote: true
trailingComma: none
bracketSpacing: true
arrowParens: avoid
overrides:
  - files: .github/**/*.yml
    options:
      tabWidth: 2
